version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media  # Mount the media directory for media files
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=your_secret_key_here
      - DEBUG=True  # Set to True for development
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - POSTGRES_DB=videos_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: videos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
