# Generated by Django 5.1.1 on 2024-09-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitles_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
    ]
