# Generated by Django 5.1.1 on 2024-09-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_subtitle_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='uploaded_at',
            new_name='upload_time',
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
    ]
