# Generated by Django 5.1.1 on 2024-09-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_rename_uploaded_at_video_upload_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='start_time',
            field=models.DurationField(),
        ) ,
    ]
